# Generated by Django 4.2 on 2025-05-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0006_eventos_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='responsable_id_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='responsable_rol',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
