# Generated by Django 4.2 on 2025-05-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0007_eventos_responsable_id_ref_eventos_responsable_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='responsable_id_ref',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='responsable_rol',
        ),
    ]
