# Generated by Django 4.2 on 2025-05-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0008_remove_eventos_responsable_id_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='responsable_rol',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='responsable_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
